# Tratando um erro específico

try:
    geek()
except NameError():
    print("Você está usando uma função inexistente")
